<a href="https://colab.research.google.com/github/cu-applied-math/appm-4600-numerics/blob/main/Lab13_Eigenvalues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 13: beyond the simple power method for eigenvalues

### Tasks
1. Code the *orthogonal iteration* and *QR iteration* and run it on the given matrix $A$
2. Code the *inverse iteration* (aka shift-and-invert power method) and run it on the given matrix $A$
3. Apply these codes to matrices that may have *complex eigenvalues* or non-unique dominant eigenvalues
4. (*Optional*) Examine the Rayleigh quotient iteration

### Deliverables
1. The output from task 1 (see below for details)
2. The output from task 2 (see below for details)

Combine these into a single PDF and upload to Canvas

### Learning objectives
- Understand the algorithms
- Examine convergence
- See what can go wrong and how complex eigenvalues affect things


*Copyright 2025, Department of Applied Mathematics, University of Colorado Boulder. Released under a BSD 3-clause license*

In [2]:
import numpy as np
import scipy.linalg as sla
from matplotlib import pyplot as plt

Let's use the following small matrix. We'll make things easy for ourselves by choosing a **symmetric** matrix, which guarantees that the eigenvalues are real

In [80]:
rng = np.random.default_rng(67)
n = 5
A = rng.integers(low=-3,high=9,size=(n,n))
A = A + A.T # make it symmetric, so eigenvalues are guaranteed to be real
print(A)
eigs = sla.eigvalsh(A)[::-1]
print(eigs)

[[12  4  8 -1  5]
 [ 4  8  2  7  3]
 [ 8  2 14 -2 -1]
 [-1  7 -2 -4  4]
 [ 5  3 -1  4 12]]
[23.56061053 15.91358247  7.7036999   2.92935241 -8.10724531]


# Task 1
Write code for both the **orthogonal iteration** and **QR iteration**.

We didn't discuss in much detail how you get your estimate of the eigenvalues, so put some thought into this. For the power method, if $\vec{x}$ (with $\|\vec{x}\|_2=1$) is our current iteration, we use the estimate $\mu = \vec{x}^\top A \vec{x}$.  So how can you generalize that when you have a matrix instead of a vector?

**Deliverable** Run both algorithms on the matrix $A$ from above, for 20 iterations.  In your PDF report, report both the *matrix* and the list of the *eigenvalues*.  If there's any apparent structure in the matrix, comment on that.

In [81]:
def orthogonal_iteration(... TODO ... ):
    ...

def QR_algorithm(... TODO ... ):
    ...

# Task 2: shift-and-invert power method / "Shifted inverse iteration" / ["inverse iteration"](https://en.wikipedia.org/wiki/Inverse_iteration)
Implement the shift-and-invert power method.  The user should supply a value for the shift, $q$, then the code performs the power method on the matrix $B=(A-qI)^{-1}$.

*Do not use the inverse explicitly!*

**Deliverable**

Run the inverse iteration code on the matrix $A$ from above, uing the shift $q$ to target the smallest (i.e., most negative) eigenvalue that you estimated using your QR iteration or orthogonal iteration.

In [86]:
... TODO ...

# Task 3: complex eigenvalues

### 4.1 QR iteration
Use the matrix $B$ below, which is assymetric and so it could have complex eigenvalues, and run the QR iteration on it. What does it converge to?

### 4.2 Power method
For the matrix $C$ below, try the power method. Does it converge? If so, does it converge to what you expect? (You can check its eigenvalues using scipy)

### 4.3 Power method
For the matrix $D$ below, try the power method. Does it converge? If so, does it converge to what you expect?


**Deliverables**
Nothing required

In [93]:
rng = np.random.default_rng(67)
n = 5
B = rng.integers(low=-3,high=9,size=(n,n))
# TODO: run QR iteration

In [99]:
C = np.array(( [[0,-25/4,0,0],[1,-4,0,0],[0,0,0,-41/4],[0,0,1,-5]]))
print(C)
# TODO: run power method

[[  0.    -6.25   0.     0.  ]
 [  1.    -4.     0.     0.  ]
 [  0.     0.     0.   -10.25]
 [  0.     0.     1.    -5.  ]]


In [105]:
rng = np.random.default_rng(67)
n = 5
D = rng.integers(low=-3,high=9,size=(n,n))
D = D - np.tril(D) + np.diag( [10,10,6,4,3])
# TODO: run power method

# Task 4 (optional): Rayleigh quotient iteration
Implement the [**Rayleigh quotient**](https://en.wikipedia.org/wiki/Rayleigh_quotient_iteration) method (a simple implementation reference is at https://www.cs.utexas.edu/~flame/Notes/NotesOnPowerMethod.pdf)

This is the inverse iteration, but uses your best guess for the eigenvalue at every iteration for the shift, so it converges very fast.

**Deliverables**
Nothing required

In [89]:
def RayleighQuotient(... TODO ... )